version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: klinik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:testing1234@postgres:5432/klinik
      - NODE_ENV=development
      - API_KEY=testing
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=testing1234
      - DB_NAME=klinik
    command: >
      sh -c "
      pnpm run migration:run &&
      pnpm start
      "
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:8080/api
      - VITE_API_KEY=testing
    ports:
      - '3000:80'
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
